Vagrant.configure(2) do |config|
  config.vm.box = "WINXP_SP3_BASE"
  config.vm.communicator = "winrm"
  config.winrm.username = "mayhack"
  config.winrm.password = "mayhack"

  config.vm.network "public_network", :adapter=>2 , ip: "10.10.86.25", :bridge => 'en1: Bridged', :mac => "080027000002"
  config.vm.network "private_network", :adapter=>3 , ip: "192.168.50.4", :mac => "080027000003", virtualbox__intnet: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
end
